apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: aspnet-test-app-kustomization

namespace: app-dev

commonLabels:
  env: dev

resources:
- ./../../base

patches:
- path: deployment.yaml
- path: ingress.yaml
