apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnet-test-app
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: aspnet-test-app
        image: cr.yamac.net/aspnet-test/app:develop
        ports:
        - containerPort: 9590
        env:
        - name: TZ
          value: Asia/Tokyo
        - name: ASPNETCORE_ENVIRONMENT
          value: Beta
        - name: ASPNETCORE_URLS
          value: http://*:9590
