apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: aspnet-test-app-kustomization

commonLabels:
  app: aspnet-test-app

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
