name: workflow_dispatch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Show Environment Variables
      run: env

    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver: docker

    - name: Docker Build
      uses: docker/build-push-action@v2
      with:
        context: .
        target: test
        push: false
